# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and commit it back to the repo
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update content

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Run Yarn script
        run: yarn content

      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Actions"
          git add .
          git commit -m "Update content"
          git push origin main
